"""File operations commands."""

import os
from pathlib import Path
import click
from rich.console import Console
from rich.syntax import Syntax
from rich.panel import Panel

console = Console()


@click.group()
def file_cmd():
    """File operations with AI assistance."""
    pass


@file_cmd.command(name='list')
@click.argument('path', default='.')
@click.option('--recursive', '-r', is_flag=True, help='List recursively')
def list_files(path, recursive):
    """List files in a directory."""
    target = Path(path)
    
    if not target.exists():
        console.print(f"[red]Path not found: {path}[/red]")
        return
    
    if target.is_file():
        console.print(f"[red]{path} is a file, not a directory[/red]")
        return
    
    pattern = "**/*" if recursive else "*"
    files = list(target.glob(pattern))
    files = [f for f in files if not any(p.startswith('.') for p in f.parts)]
    
    for f in sorted(files):
        rel_path = f.relative_to(target)
        if f.is_dir():
            console.print(f"[blue]📁 {rel_path}/[/blue]")
        else:
            size = f.stat().st_size
            size_str = f"{size:,} B" if size < 1024 else f"{size/1024:.1f} KB"
            console.print(f"  📄 {rel_path} [dim]({size_str})[/dim]")


@file_cmd.command()
@click.argument('path')
def read(path):
    """Read and display a file with syntax highlighting."""
    target = Path(path)
    
    if not target.exists():
        console.print(f"[red]File not found: {path}[/red]")
        return
    
    if target.is_dir():
        console.print(f"[red]{path} is a directory[/red]")
        return
    
    try:
        content = target.read_text()
        
        # Detect language from extension
        ext = target.suffix.lstrip('.')
        lang_map = {
            'py': 'python',
            'js': 'javascript',
            'ts': 'typescript',
            'jsx': 'jsx',
            'tsx': 'tsx',
            'rs': 'rust',
            'go': 'go',
            'yaml': 'yaml',
            'yml': 'yaml',
            'json': 'json',
            'md': 'markdown',
            'html': 'html',
            'css': 'css',
            'sh': 'bash',
            'sql': 'sql',
        }
        
        syntax = Syntax(
            content,
            lang_map.get(ext, 'text'),
            theme='monokai',
            line_numbers=True,
            word_wrap=True
        )
        
        console.print(Panel(syntax, title=str(target)))
        
    except Exception as e:
        console.print(f"[red]Error reading file: {e}[/red]")


@file_cmd.command()
@click.argument('path')
@click.option('--content', '-c', help='Initial content')
@click.option('--agent', '-a', help='Agent to help create the file')
def create(path, content, agent):
    """Create a new file, optionally with AI assistance."""
    target = Path(path)
    
    if target.exists():
        if not click.confirm(f"File {path} exists. Overwrite?"):
            return
    
    # Create parent directories if needed
    target.parent.mkdir(parents=True, exist_ok=True)
    
    if agent and not content:
        console.print(f"[cyan]Asking {agent} agent to generate content...[/cyan]")
        # In real implementation, this would call the agent
        content = f"# Generated by {agent} agent\n# TODO: Implement"
    
    target.write_text(content or "")
    console.print(f"[green]Created:[/green] {path}")


@file_cmd.command()
@click.argument('path')
@click.option('--agent', '-a', required=True, help='Agent to perform the edit')
@click.option('--prompt', '-p', required=True, help='Instructions for the edit')
def edit(path, agent, prompt):
    """Edit a file using an AI agent."""
    target = Path(path)
    
    if not target.exists():
        console.print(f"[red]File not found: {path}[/red]")
        return
    
    console.print(f"[cyan]Asking {agent} agent to edit {path}...[/cyan]")
    console.print(f"[dim]Instructions: {prompt}[/dim]\n")
    
    # Read current content
    current_content = target.read_text()
    
    # In real implementation, this would:
    # 1. Send file content + prompt to agent
    # 2. Get edited content back
    # 3. Show diff
    # 4. Apply changes
    
    console.print("[yellow]Current content:[/yellow]")
    console.print(current_content[:500] + "..." if len(current_content) > 500 else current_content)
    
    console.print("\n[dim](In real implementation, agent would provide edited content here)[/dim]")


@file_cmd.command()
@click.argument('source')
@click.argument('destination')
def move(source, destination):
    """Move or rename a file."""
    src = Path(source)
    dst = Path(destination)
    
    if not src.exists():
        console.print(f"[red]Source not found: {source}[/red]")
        return
    
    dst.parent.mkdir(parents=True, exist_ok=True)
    src.rename(dst)
    console.print(f"[green]Moved:[/green] {source} → {destination}")


@file_cmd.command()
@click.argument('path')
@click.confirmation_option(prompt='Are you sure you want to delete this file?')
def delete(path):
    """Delete a file."""
    target = Path(path)
    
    if not target.exists():
        console.print(f"[red]File not found: {path}[/red]")
        return
    
    if target.is_dir():
        import shutil
        shutil.rmtree(target)
        console.print(f"[green]Deleted directory:[/green] {path}")
    else:
        target.unlink()
        console.print(f"[green]Deleted file:[/green] {path}")
