package main

import (
	"net/http"
	"os/exec"
	"strings"

	"github.com/gin-gonic/gin"
)

// TaskRequest represents a task from the orchestrator
type TaskRequest struct {
	TaskID      string   `json:"task_id" binding:"required"`
	Description string   `json:"description" binding:"required"`
	Files       []string `json:"files"`
	Context     map[string]interface{} `json:"context"`
}

// TaskResponse represents the result
type TaskResponse struct {
	TaskID   string `json:"task_id"`
	Status   string `json:"status"`
	Result   string `json:"result,omitempty"`
	Error    string `json:"error,omitempty"`
}

func main() {
	r := gin.Default()

	// Health check
	r.GET("/health", func(c *gin.Context) {
		c.JSON(http.StatusOK, gin.H{
			"status": "healthy",
			"agent":  "ops-engineer",
			"tools": []string{
				"docker",
				"kubernetes",
				"terraform",
				"helm",
			},
		})
	})

	// Execute task
	r.POST("/execute", func(c *gin.Context) {
		var req TaskRequest
		if err := c.ShouldBindJSON(&req); err != nil {
			c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
			return
		}

		// Process the task
		result := processTask(req)
		c.JSON(http.StatusOK, result)
	})

	// Docker operations
	r.POST("/docker/build", handleDockerBuild)
	r.POST("/docker/compose", handleDockerCompose)

	// Kubernetes operations
	r.POST("/k8s/apply", handleK8sApply)
	r.POST("/k8s/generate", handleK8sGenerate)

	// Terraform operations
	r.POST("/terraform/init", handleTerraformInit)
	r.POST("/terraform/plan", handleTerraformPlan)

	r.Run(":8082")
}

func processTask(req TaskRequest) TaskResponse {
	desc := strings.ToLower(req.Description)

	// Simple keyword-based processing
	if strings.Contains(desc, "docker") || strings.Contains(desc, "container") {
		return generateDockerfile(req)
	}

	if strings.Contains(desc, "kubernetes") || strings.Contains(desc, "k8s") {
		return generateK8sManifest(req)
	}

	if strings.Contains(desc, "terraform") || strings.Contains(desc, "infrastructure") {
		return generateTerraform(req)
	}

	return TaskResponse{
		TaskID: req.TaskID,
		Status: "completed",
		Result: "Ops Engineer received task: " + req.Description + "\n\" +
			"I specialize in Docker, Kubernetes, Terraform, and CI/CD configurations.",
	}
}

func generateDockerfile(req TaskRequest) TaskResponse {
	dockerfile := `# Generated by Ops Engineer Agent
FROM node:20-alpine

WORKDIR /app

COPY package*.json ./
RUN npm ci --only=production

COPY . .

EXPOSE 3000

USER node

CMD ["node", "server.js"]
`
	return TaskResponse{
		TaskID: req.TaskID,
		Status: "completed",
		Result: dockerfile,
	}
}

func generateK8sManifest(req TaskRequest) TaskResponse {
	manifest := `# Generated by Ops Engineer Agent
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  labels:
    app: myapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: app
        image: myapp:latest
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  selector:
    app: myapp
  ports:
  - port: 80
    targetPort: 3000
  type: ClusterIP
`
	return TaskResponse{
		TaskID: req.TaskID,
		Status: "completed",
		Result: manifest,
	}
}

func generateTerraform(req TaskRequest) TaskResponse {
	terraform := `# Generated by Ops Engineer Agent
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }
}

provider "aws" {
  region = var.aws_region
}

variable "aws_region" {
  default = "us-west-2"
}

resource "aws_ecs_cluster" "app" {
  name = "my-app-cluster"
  
  setting {
    name  = "containerInsights"
    value = "enabled"
  }
}

output "cluster_id" {
  value = aws_ecs_cluster.app.id
}
`
	return TaskResponse{
		TaskID: req.TaskID,
		Status: "completed",
		Result: terraform,
	}
}

func handleDockerBuild(c *gin.Context) {
	var req struct {
		Path string `json:"path"`
		Tag  string `json:"tag"`
	}
	if err := c.ShouldBindJSON(&req); err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
		return
	}

	cmd := exec.Command("docker", "build", "-t", req.Tag, req.Path)
	output, err := cmd.CombinedOutput()

	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{
			"error":  err.Error(),
			"output": string(output),
		})
		return
	}

	c.JSON(http.StatusOK, gin.H{
		"status": "success",
		"output": string(output),
	})
}

func handleDockerCompose(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{"status": "docker compose handler"})
}

func handleK8sApply(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{"status": "k8s apply handler"})
}

func handleK8sGenerate(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{"status": "k8s generate handler"})
}

func handleTerraformInit(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{"status": "terraform init handler"})
}

func handleTerraformPlan(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{"status": "terraform plan handler"})
}
